FROM node:22-alpine

WORKDIR /app

# Installer les dépendances
COPY package.json package-lock.json ./
RUN npm ci

# Copier le reste des fichiers
COPY . .

ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_PUBLIC_API_URL=http://localhost/api/v1

EXPOSE 3000

CMD ["npm", "run", "dev"]
